name: Syntax and style checking
on:
  push:
    branches: main
  pull_request:

jobs:
  check_syntax:
    name: Luacheck
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        run: |
          sudo apt update
          sudo apt install luarocks
          sudo luarocks install luacheck

      - name: Lint
        run: make lint
